base/urls.py
from django.urls import path

from base import views

app_name = "base"
urlpatterns = [
    path("", views.base, name="home"),
    path("inherit/", views.inherit)
]

django_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("base/", include("base.urls")),
    path("blog/", include("blog.url")),
    path("shopping/", include("shopping.urls")),
    path("payment/", include("payment.urls")),
    path("local/", include("local.urls")),
]

landing/urls.py
from django.urls import path

from landing import views

app_name = "landing"
urlpatterns = [
    path("", views.index, name ="home")
]

local/urls.py
from django.urls import path

from local import views

app_name = "local"
urlpatterns = [
    path("local-shops", views.index, name="home")
]

payment/urls.py
from django.urls import path

from payment import views


urlpatterns = [
    path("cart/", views.index),
    path("purchase/", views.purchase),
    path("complete/", views.complete),
]

shopping/urls.py
from django.urls import path

from shopping import views

app_name = "shop"
urlpatterns = [
    path("shop", views.index, name="home"),
    path("admin", views.admin),
    path("item", views.item)
]

base/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField()
    likes = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}, {self.content[:20]}"

landing/models.py
from django.db import models

# Create your models here.

payment/models.py
from django.db import models

# Create your models here.

class Order(models.Model):
    product_name = models.TextField()
    price = models.TextField()
    payment_method = models.TextField()
    ordered_at = models.DateTimeField(auto_now_add=True)

base/views.py
from django.shortcuts import render

def base(request):
    context = {

    }

    return render(request, "base.html", context)

def inherit(request):
    context = {

    }
    return render(request, "base_ih.html",context)

blog/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

from blog.models import Post

def blog_home(request):
    post_list = Post.objects.all()
    context ={
        "post_list": post_list,
    }
    return render(request, "blog/index.html", context)


def blog_post(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        "post": post
    }
    return render(request, "blog/post.html", context)

def blog_post_edit(request, post_id):
    target_post = Post.objects.get(id=post_id)
    if request.method == "GET":
        context = {
           "post": target_post
        }
        return render(request, "blog/edit.html", context)
    elif request.method == "POST":
        target_post.title = request.POST["title"]
        target_post.content =request.POST["content"]
        target_post.save()
        return HttpResponseRedirect(f"/blog/post/{post_id}/")

def blog_create(request):
    if request.method == "POST":
        new_post = Post()
        new_post.title = request.POST["title"]
        new_post.content = request.POST["content"]
        new_post.likes = 0
        new_post.save()
        return HttpResponseRedirect("/blog/home/")

    return render(request, "blog/create.html")

def blog_post_delete(request, post_id):
    target_post = Post.objects.get(id=post_id)
    if request.method == "GET":
        target_post = Post.objects.get(id=post_id)
        context = {
            "post": target_post
        }
        return render(request, "blog/delete.html", context)
    elif request.method == "POST":
        target_post.delete()
        return HttpResponseRedirect("/blog/home/")

landing/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "landing/index.html")

local/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "local/index.html")

payment/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "payment/index.html")

def purchase(request):
    return render(request, "payment/purchase.html")

def complete(request):
    return render(request, "payment.complete.html")

shopping/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "shopping/index.html")

def admin(request):
    return render(request, "shopping/admin.html")

def item(request):
    return render(request, "shopping/item.html")

blog/templates/blog/blog-home.html
{% extends "index.html" %}
{% block title %} Blog Home {% endblock %}

{% block content %}
    {% if post_list %}
    <ol>
        {% for post in post_list %}
        <li><a href="{% url 'post-view' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
    </ol>
    {% else %}
    <h4>No post</h4>
    {% endif %}
    <p>Total Posts: {{ post_list|length }}</p>
    <a href="{%% url 'post-write' %}">Write Post</a>
{% endblock %}

blog/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog create</title>
</head>
<body>
    <h1>Blog create</h1>
    <h2>Write Post Page</h2>
    <form action="/blog/create/" method="POST" id="create">
        {% csrf_token %}
        Title: <input type="text" name="title"/>
        <input type="submit" />
    </form>
    <textarea name="content" form="create"> Enter Content</textarea>
</body>
</html>

blog/templates/blog/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ post.title }} - Delete </title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <form action="/blog/post-delete/{{ post.id }}/" method="post">
        {% csrf_token %}
        <h3>Are you sure?</h3>
        <input type="submit"/>
    </form>
</body>
</html>

blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog create</title>
</head>
<body>
    <h1>Blog edit</h1>
    <h2>Edit Post Page</h2>
    <form action="/blog/post-edit/{{ post.id }}/" id="blog-edit", method="POST">
        {% csrf_token %}
        Title: <input type="text" name="title" value="{{ post.title }}"/>
        <input type="submit" />
    </form>
    <textarea name="content" form="blog-edit"> {{ post.content }}</textarea>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Home</title>
</head>
<body>
    <p>
        <span class="link"><a href="{% url 'landing:home' %}">Home</a></span>
        <span class="link"><a href="{% url 'blog:home' %}">Blog</a></span>
        <span class="link"><a href="{% url 'shop:home' %}">Shops</a></span>
        <span class="link"><a href="{% url 'local:home' %}">Find Shops</a></span>
    </p>
    <h1>Blog home</h1>
    {% if post_list %}
    <ol>
        {% for post in post_list %}
        <a href="/blog/post/{{ post.id }}"><li>{{ post.title }}</li></a>
        {% endfor %}
    </ol>
    {% else %}
    <h4>No post</h4>
    {% endif %}
    <p>Total Posts: {{ post_list|length }}</p>
    <a href="/blog/create/">Write Post</a>
</body>
</html>

blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ post.title }}</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p>작성 시간 {{ post.created_at|date:"m\월 d\일"}}</p>
    <a href="/blog/post-edit/{{ post.id }}/">edit</a>&nbsp;
    <a href="/blog/post-delete/{{ post.id }}/">delete</a>
</body>
</html>

landing/templates/landing/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crystal's Django</title>
</head>
<body>
    <p>
        <span class="link"><a href="{% url 'landing:home' %}">Home</a></span>
        <span class="link"><a href="{% url 'blog:home' %}">Blog</a></span>
        <span class="link"><a href="{% url 'shop:home' %}">Shops</a></span>
        <span class="link"><a href="{% url 'local:home' %}">Find Shops</a></span>
    </p>
    <h1>Nice to meet you, Django!</h1>
</body>
</html>

local/templates/local/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>local-shops</title>
</head>
<body>
    <p>
        <span class="link"><a href="{% url 'landing:home' %}">Home</a></span>
        <span class="link"><a href="{% url 'blog:home' %}">Blog</a></span>
        <span class="link"><a href="{% url 'shop:home' %}">Shops</a></span>
        <span class="link"><a href="{% url 'local:home' %}">Find Shops</a></span>
    </p>
    <h1>local-shops</h1>
</body>
</html>

payment/templates/payment/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>payment complete</title>
</head>
<body>
    <h1>payment complete</h1>
</body>
</html>

payment/templates/payment/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>payment cart</title>
</head>
<body>
    <p>
        <span class="link"><a href="{% url 'landing:home' %}">Home</a></span>
        <span class="link"><a href="{% url 'blog:home' %}">Blog</a></span>
        <span class="link"><a href="{% url 'shop:home' %}">Shops</a></span>
        <span class="link"><a href="{% url 'local:home' %}">Find Shops</a></span>
    </p>
    <h1>payment cart</h1>
</body>
</html>

payment/templates/payment/purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>payment purchase</title>
</head>
<body>
    <h1>payment purchase</h1>
</body>
</html>

shopping/templates/shopping/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>shopping admin</title>
</head>
<body>
    <h1>shopping admin</h1>
</body>
</html>

shopping/templates/shopping/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>shopping home</title>
</head>
<body>
    <p>
        <span class="link"><a href="{% url 'landing:home' %}">Home</a></span>
        <span class="link"><a href="{% url 'blog:home' %}">Blog</a></span>
        <span class="link"><a href="{% url 'shop:home' %}">Shops</a></span>
        <span class="link"><a href="{% url 'local:home' %}">Find Shops</a></span>
    </p>
    <h1>shopping home</h1>
</body>
</html>

shopping/templates/shopping/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>shopping item</title>
</head>
<body>
    <h1>shopping item</h1>
</body>
</html>